require("alex.plugins-setup")
require("alex.core.options")
require("alex.core.keymaps")
require("alex.core.colorscheme")
require("alex.plugins.comment")
require("alex.plugins.neosolarized")
require("alex.plugins.nvim-tree")
require("alex.plugins.lualine")
